### ISSUE TITLE
Robot goes to full speed reverse

### ISSUE THREAD

**Issue by anfederman** [UbiquityRobotics/demos#4]
We tried running magni_demos fiducial follow. I copied the raspicam 430 launch file into opt/ros/kinetic...raspicam_node.  aupon launching the fiducial follow, the newer magni went beastmode full rereverse.  didn't stop until we shut power.  killing the node and shutdown on the pi didn't help.

**Comment by jim-v** [comment]
What is the output of   `apt-cache policy ros-kinetic-ubiquity-motor`?

It's better to run `apt-get upgrade` than to copy files into  `/opt/ros`.

**Comment by jim-v** [comment]
I have not been able to reproduce this.  I ran `roslaunch magni_demos fiducial_follow.launch`, and the robot behaved as expected when shown fiducial 49.

**Comment by jim-v** [comment]
The problem with manually copying files into `/opt/ros/kinetic/share/raspicam_node` is that they will be left behind if you remove the `raspicam_node` package.  From a support perspective, it's better if you install from debs, so that we can try to reproduce issues with the exact same configuration.

**Comment by rohbotics** [comment]
Is this issue close-able?

As I understand it this was on the blue demo robot, and it no longer happens.
